# Generated by Django 3.0.8 on 2020-07-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0003_auto_20200712_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_author',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
